### ISSUE TITLE
Pass a GlobalEnvironment into the Runtime::initialize()

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-composer-plugin#2]
## Context

As you can find in `https://github.com/jenshaase/phel-composer-plugin/blob/master/src/DumpRuntime.php:67`:

```php
$template = <<<EOF
<?php
// @generated by Phel
use Phel\Runtime;
require __DIR__ .'/autoload.php';
\$rt = Runtime::initialize();
EOF;
```

## What

The `Runtime::initialize()` doesn't provide any argument because the signature of that named constructor allows you to do it this way. I was thinking about changing the signature of that name constructor to force the `GlobalEnvironmentInterface` argument every time when you want to initialize the Runtime. The `Phel\Runtime` would look like this:

```php
// Runtime:62
public static function initialize(
    ?GlobalEnvironmentInterface $globalEnv,
    ?string $cacheDirectory = null
): self 
```

## Reason

In order to decouple the `Phel\Runtime` from the `GlobalEnvironment`. This is the change that I would like to do in Phel project, but it's blocked by the PhelRuntime autoload (this phel-composer-plugin).

```diff
// Runtime:70
- public static function initialize(
-     ?GlobalEnvironmentInterface $globalEnv = null,
-     ?string $cacheDirectory = null
- ): self {
-     if (self::$instance !== null) {
-         throw new RuntimeException('Runtime is already initialized');
-     }
- 
-     self::$instance = new self(
-         $globalEnv ?? new GlobalEnvironment(), // <--- THIS IS THE ACTUAL CHANGE
-         $cacheDirectory
-     );
- 
-     return self::$instance;
- }
+ public static function initialize(
+     ?GlobalEnvironmentInterface $globalEnv,
+     ?string $cacheDirectory = null
+ ): self {
+     if (self::$instance !== null) {
+         throw new RuntimeException('Runtime is already initialized');
+     }
+ 
+     self::$instance = new self($globalEnv, $cacheDirectory);
+ 
+     return self::$instance;
+ }
```

## Acceptance Criteria

- Change that template (from the DumpRuntime.php:67) in order to pass the concrete `GlobalEnvironment` while initializing the `Runtime`.

**Comment by jenshaase** [comment]
Hi,

this plugin should need to know as little as possible. Therefore, there should be a method in the Phel Project that initializes the runtime by a method call without arguments. If you think `Runtime::initialize` is not the best way to do it, I would suggest to introduce a Factory Class to handle this. What do you think?

Best regards,
Jens

**Comment by Chemaclass** [comment]
Yes, thanks for the idea, @jenshaase. This is the PR https://github.com/jenshaase/phel-composer-plugin/pull/3
